### PR TITLE
F tester base fixes

### PR DESCRIPTION
**Pull request by martynassateika**
Some fixes for the classes in `/libraries`.

### CODE REVIEW

**Comment by martynassateika** [comment]
I think it might be worth releasing a new version of the tester module to master (it's been nearly two years now since 1.0). Maybe 1.0.1, since it's only been bug-fixes? :-)

People might not like it if they add the module, it's on an out-dated `master` by default, and they immediately bump into some kind of issue.

**Comment by daylightstudio** [comment]
Sounds good. What kind of issues were you bumping into (it's been a while since I've looked at that one)?

**Comment by daylightstudio** [comment]
Actually... I see the other pull request referencing some issues.

**Comment by martynassateika** [comment]
No issues with the tester module itself right now :-) But if `master` is outdated then people get access to 2-year old code.

I see you just merged to master. Great stuff. Just note that the version numbers in FUEL-CMS and this module are formatted differently:

https://github.com/daylightstudio/FUEL-CMS/blob/master/fuel/modules/fuel/config/fuel_constants.php

"1.4.2" in FUEL CMS vs "1.01" here. I think "1.0.1" should be used if we're following semantic versioning.

**Comment by martynassateika** [comment]
Thanks for the fix!

**Comment by daylightstudio** [comment]
Thanks for the catch!

**Pull request merged**
